version: '3'

services:
  superset:
      build:
        context: ./superset
        dockerfile: dockerfile
      container_name: superset
      environment:
        - ADMIN_USERNAME=xxx
        - ADMIN_EMAIL=xxx
        - ADMIN_PASSWORD=xxx
        - CSRF_ENABLED = False
      ports:
        - '8088:8088'

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxx
    ports:
      - '5432:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: xxx
      PGADMIN_DEFAULT_PASSWORD: xxx
    depends_on:
      - postgres
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net:
